version: "3"

services:
    postgres-database:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "admin"
        ports:
            - "15432:5432"
        networks:
            - postgres-compose-network

    teste-pgadmin-compose:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "dalio@hotmail.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "16543:80"
        depends_on:
            - postgres-database
        networks:
            - postgres-compose-network

networks:
    postgres-compose-network:
        driver: bridge
